### ISSUE TITLE
com.hcc

### ISSUE THREAD

**Issue by exception** [HypixelCommunityClient/HCC#16]
Not owned by any of your team, should be using a different package.

:feelsbadman:

**Comment by boomboompower** [comment]
It'll be refactored later + its a random mod so who really cares
:feelsbadman:

**Comment by emanh1** [comment]
the team owns it



wat

**Comment by VRCube** [comment]
we will use whatever package we want.
~~No throttling~~

**Comment by exception** [comment]
🤔
