### ISSUE TITLE
gradle build error

### ISSUE THREAD

**Issue by emanh1** [HypixelCommunityClient/HCC#7]
`E:\gradle-4.1\bin>gradle build

> Configure project :
This mapping 'stable_20' was designed for MC 1.8.8! Use at your own peril.

> Task :compileJava
Potential refmap conflict. Duplicate refmap name mixin.hcc.refmap.json specified for sourceSet main, already defined for sourceSet main
ERROR StatusLogger Unable to locate a logging implementation, using SimpleLogger
E:\gradle-4.1\bin\build\sources\main\java\com\google\common\hash\BloomFilter.java:64: error: cannot find symbol
  interface Strategy extends Serializable {
                             ^
  symbol:   class Serializable
  location: class BloomFilter<T>
  where T is a type-variable:
    T extends Object declared in class BloomFilter
E:\gradle-4.1\bin\build\sources\main\java\com\google\common\primitives\UnsignedBytes.java:27: warning: Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
               ^
Note: SpongePowered MIXIN Annotation Processor Version=0.6.4
Note: ObfuscationServiceMCP supports type: "searge"
Note: ObfuscationServiceMCP supports type: "notch"
error: cannot access InverseEntry
  bad class file: C:\Users\nhama\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\17.0\9c6ef172e8de35fd8d4d8783e4821e57cdef7445\guava-17.0.jar(com/google/common/collect/HashBiMap$Inverse$1$1$InverseEntry.class)
    undeclared type variable: K
    Please remove or make sure it appears in the correct subdirectory of the classpath.
error: cannot access MapEntry
  bad class file: C:\Users\nhama\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\17.0\9c6ef172e8de35fd8d4d8783e4821e57cdef7445\guava-17.0.jar(com/google/common/collect/HashBiMap$EntrySet$1$MapEntry.class)
    undeclared type variable: K
    Please remove or make sure it appears in the correct subdirectory of the classpath.
E:\gradle-4.1\bin\build\sources\main\java\com\google\common\primitives\UnsignedBytes.java:27: warning: Unsafe is internal proprietary API and may be removed in a future release
import sun.misc.Unsafe;
               ^
3 errors
2 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
7 actionable tasks: 7 executed`

stacktrace : https://pastebin.com/yvw0LYQJ

**Comment by KevinPriv** [comment]
Should be fixed
